boy=input("boy name: ")
girl = input('girl name:')
b=input("boy age: ")
g=input("girl age: ")
diff=abs(int(b)-int(g))
print(boy + ' loves ' + girl + ".Age difference is" + str(diff))
print(f"{boy} loves {girl}. Age difference is {diff}")